### ISSUE TITLE
Function to remove color coding

### ISSUE THREAD

**Issue by tylerFowler** [Marak/colors.js#104]
It would be nice to offer a utility function to take a string and remove any styling from it. I do logging in a Node app where I like to use colors for the terminal but I also write the logs to a file stream:

like this
```coffee
console.log = (d) ->
  logFile.write "#{util.format d}\n"
  process.stdout.write "#{util.format d}\n"
```

And when I do this the file ends up with stuff like
`[34mApp 16:39:54 | [INFO]: Successfully created Express app[39m`

**Comment by pksunkara** [comment]
Note: A function is already used inside the library, [here](https://github.com/Marak/colors.js/blob/master/lib/colors.js#L55)

**Comment by shazron** [comment]
Not documented, but I used .strip and it works
