### ISSUE TITLE
color after inverse

### ISSUE THREAD

**Issue by kilianc** [Marak/colors.js#11]
```
console.log('white on green'.green.bold.inverse.white);
```

should be a white string on a green background.

**Comment by DABH** [comment]
Is this still an issue?

**Comment by Qix-** [comment]
No, lol. I submitted a patch for reverse video rendering for Windows to Node.js years ago.

As an aside, the above is probably one of my earlier comments on Github. 💥

**Comment by DABH** [comment]
Ha, excellent :) Thanks for the fast reply after so many years :)
