### ISSUE TITLE
`enabled` doesn't work

### ISSUE THREAD

**Issue by eprev** [Marak/colors.js#113]
It seems it doesn't work anymore in (v1.0.3 — latest published version).

``` js
require('colors').enabled = false;
console.log('hello'.red);
```

It will print out red line.

**Comment by eprev** [comment]
It works in v1.1.0. Are you going to you publish this version?

**Comment by pksunkara** [comment]
@eprev @Marak is reviewing the v1.1.0 now and should be able to publish it soon.

**Comment by ttsirkia** [comment]
Also the --no-color option has no effect.

**Comment by pksunkara** [comment]
That has been fixed too.

**Comment by robby** [comment]
@pksunkara @Marak @eprev is v1.1.0 able to be published to npm?

**Comment by DABH** [comment]
Please reopen if this is still an issue.  Thanks!
