### ISSUE TITLE
'safe' colors not showing up when using foreman

### ISSUE THREAD

**Issue by fiznool** [Marak/colors.js#121]
When running the node app with [foreman](https://github.com/ddollar/foreman), strings colored with `colors/safe` do not display. This is an issue since Heroku uses foreman to run node apps, and so logs will not show up in color.

Using the following `Procfile`:

```
web: node index.js
```

The following code produces colorized output:

``` js
require('colors');
console.log('this should be red'.red);
```

![screenshot from 2015-04-18 10 15 54](https://cloud.githubusercontent.com/assets/820863/7214814/21dd9702-e5b4-11e4-9f44-2992b20b2715.png)

but the following does not:

```
var colors = require('colors/safe');
console.log(colors.red('this should be red'));
```

![screenshot from 2015-04-18 10 16 34](https://cloud.githubusercontent.com/assets/820863/7214815/2887a1d8-e5b4-11e4-8f4c-3b48c2c98211.png)

**Comment by fiznool** [comment]
For reference, this is also an issue when using `grunt-express-server`.

``` js
// Gruntfile.js
module.exports = function(grunt) {
  grunt.loadNpmTasks('grunt-express-server');
  grunt.initConfig({
    express: {
      dev: {
        options: {
          script: 'index.js'
        }
      }
    }
  });
};
```

![screenshot from 2015-04-18 10 32 52](https://cloud.githubusercontent.com/assets/820863/7214869/4c1f2420-e5b6-11e4-9a5d-616d61d19324.png)

**Comment by Chocobozzz** [comment]
Same here with **grunt-express-server". It's quite annoying since we can't have a colorized output with Winston using Grunt for example.

**Comment by iDVB** [comment]
+1  (grunt-express-server, wilson)

**Comment by fiznool** [comment]
It appears that there is a workaround:

``` js
require('colors').enabled = true
```

**Comment by DABH** [comment]
Yep, you can force colors to true (check out lib/system/supports-colors.js for additional command line args etc. you can pass to force colors to be enabled).  Please feel free to re-open if this issue persists with `colors@next`.  Thanks!
