### ISSUE TITLE
Error when combining colors

### ISSUE THREAD

**Issue by bcaudan** [Marak/colors.js#124]
When I try to combine colors, as it is pointed in the bottom of the Readme:

``` node
var colors = require('colors');

colors.setTheme({
    custom: ['red', 'underline']
});

console.log('test'.custom);
```

I run into this error:

```
TypeError: Object #<Object> has no method 'red'
    at String.custom (/private/tmp/plop/node_modules/colors/lib/extendStringPrototype.js:89:44)
```

Am I doing something wrong?

**Comment by PeterDaveHello** [comment]
+1

**Comment by PeterDaveHello** [comment]
works in nodejs' shell(!?), but not work in the scripted code

**Comment by Marak** [comment]
Seems related to #72 

Ping @konsumer

**Comment by LuJyKa** [comment]
it don't work, console give a info on
node_modules\colors\lib\extendStringPrototype.js:89
              ret = exports[theme[prop][t]](ret);

**Comment by konsumer** [comment]
I will take a look once I get a chance. For now,  try the other syntax `colors.custom('test')`

**Comment by konsumer** [comment]
Hmm, this was working before, but I can't seem to get either code style to work:

```javascript
var colors = require('colors');

colors.setTheme({
  info: 'green',
  link: ['underline', 'blue']
});

console.log(colors.info('Listening on ') + colors.link('http://0.0.0.0:8080'));
```

causes this error:

```
console.log(colors.info('Listening on ') + colors.link('http://0.0.0.0:8080'))
                                                  ^
TypeError: undefined is not a function
```

I also get that error when I change it to this:

```javascript
console.log('Listening on '.info + 'http://0.0.0:8080'.link);
```

Both are related to the `link` array, and when I remove it, I don't get an error.

I am confused. As I said, this was working fine. I will play around with it some more, and see if I can figure out what's wrong.

**Comment by konsumer** [comment]
If I do this:

```javascript
var colors = require('./node_modules/colors/lib/colors.js');

colors.setTheme({
  info: 'green',
  link: ['underline', 'blue']
});

console.log(colors.info('Listening on ') + colors.link('http://0.0.0.0:8080'));
```

It works fine. I wonder if something funny is happening with the string prototype stuff...

**Comment by konsumer** [comment]
Oh, duh! you've got another `colors.setTheme` defined in `extendStringPrototype.js` that doesn't understand arrays. Is this new? I will make another PR.

**Comment by konsumer** [comment]
nice!

**Comment by Marak** [comment]
Should be resolved now? Let me know if it's still not working.

Thanks!

**Comment by konsumer** [comment]
Yup, just about to PR same code. Thanks!

**Comment by Marak** [comment]
What error?

That syntax is working here.

**Comment by konsumer** [comment]
```
test.js:9
console.log(colors.info('Listening on ') + colors.link('http://0.0.0.0:8080'))
                                                  ^
TypeError: undefined is not a function
```

**Comment by Marak** [comment]
I see now. You'll have to merge the setTheme methods I think. Possibly applyTheme.

If you can sort out a fix that would be great. If not, I can try tomorrow.

**Comment by konsumer** [comment]
I don't think that really fits your style, but it does the trick.

**Comment by adamfowleruk** [comment]
I've just hit this issue on colors 1.1.2:-

var colors = require('colors/safe');
colors.setTheme({ title: ['yellow','bold'] });
console.log(colors.title("some title"));

results in:-
error: uncaughtException date=Wed Jan 20 2016 07:29:18 GMT+0000 (GMT), pid=15912, uid=503, gid=20, cwd=/Users/adamfowler/Documents/marklogic/git/exampleforms, execPath=/usr/local/bin/node, version=v0.10.33, argv=[node, /usr/local/bin/mljsadmin, --capture=workplace], rss=27926528, heapTotal=17603072, heapUsed=7197080, loadavg=[1.4140625, 1.37939453125, 1.31298828125], uptime=103222, trace=[column=42, file=/Users/adamfowler/Documents/marklogic/git/mlnodetools/node_modules/colors/lib/colors.js, function=Object.colors.(anonymous function) [as title], line=125, method=colors.(anonymous function) [as title], native=false, column=22, file=/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js, function=title, line=97, method=null, native=false, column=5, file=/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js, function=targets.capture_workplace, line=569, method=capture_workplace, native=false, column=15, file=/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js, function=, line=1192, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=497, method=Module.runMain, native=false, column=16, file=node.js, function=startup, line=119, method=null, native=false], stack=[TypeError: Property 'function (obj) {,     var i = this.length;,     while (i--) {,       if (this[i] === obj) {,         return true;,       },     },     return false;,   }' of object #<Object> is not a function,     at Object.colors.(anonymous function) [as title] (/Users/adamfowler/Documents/marklogic/git/mlnodetools/node_modules/colors/lib/colors.js:125:42),     at title (/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js:97:22),     at targets.capture_workplace (/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js:569:5),     at Object.<anonymous> (/Users/adamfowler/Documents/marklogic/git/mlnodetools/src/util/mljsadmin.js:1192:15),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Function.Module.runMain (module.js:497:10),     at startup (node.js:119:16)]
