### ISSUE TITLE
Official way to combine colors with bunyan

### ISSUE THREAD

**Issue by ORESoftware** [Marak/colors.js#125]
Is there an official way to use NPM colors with NPM Bunyan?

https://www.npmjs.com/package/bunyan

**Comment by f03lipe** [comment]
+1 I'd like this.

**Comment by f03lipe** [comment]
Piping colors.js output through bunyan makes the

```javascript
if (process.stdout && !process.stdout.isTTY) {
  return false;
}
```
condition in `supports-color.js` to return false, making `colors.supportsColor` and `colors.enabled` both false.

One ugly fix is to monkey-patch colors as soon as its required.

```javascript
var colors = require("colors")
colors.enabled = true
```

Another one is to pass `--color` or `--color=true` or `--color=always` (a little flamboyant, lol), as argv.

Hope it helps.

**Comment by DABH** [comment]
Does colors.enabled work better with bunyan using `colors@next`?  Feel free to open a PR if you have any specific changes that would improve integration here.

**Comment by DABH** [comment]
Closing this for now due to lack of activity.  Thanks!
