### ISSUE TITLE
Colors not working anymore with the latest version of Express?

### ISSUE THREAD

**Issue by tciuro** [Marak/colors.js#130]
Hello,

I just upgraded to `express 4.12.4` and `colors 1.1.2`. My project used to print out colored log statements fine until I upgraded. I also noticed that express' own log statements have also stopped working. Now everything prints in black. Any idea what may be happening?

Thanks!

**Comment by tciuro** [comment]
I have put aside the `colors` directory and replaced it with the older one I had, `version 1.0.3`. Turns out, it works fine. So something broke between `1.0.3` and `1.1.2`.

**Comment by Marak** [comment]
Working here.

**Comment by tciuro** [comment]
Yup, I just wrote the simplest Express app and colors prints out fine! I'm baffled. What could make colors `1.0.3` work and `1.1.2` don't? Any ideas?

**Comment by Marak** [comment]
Without you showing any reproducible code it's impossible for any of us to know if the problem is specific to your environment.
