### ISSUE TITLE
Can set colors.enable with a ENV variable

### ISSUE THREAD

**Issue by emilioplatzer** [Marak/colors.js#135]
Can you add this feature please?

Some enviroment variable (may be `set FORCE_COLOR = always`) override TTY detection. 
## Case of use

spawn a command that have many subcommands (i.e. call npm) and want (because can pipe) to receive the colored stdout and stderr streams. 
## reason

I could not use `--color=always` because some command does not pass that argumento to their own childs. 
## changes

I supouse that only need to touch `lib/system/supports-colors.js` like this:

``` js
//...
  if (argv.indexOf('--color') !== -1 ||
    argv.indexOf('--color=true') !== -1 ||
    argv.indexOf('--color=always') !== -1) {
    return true;
  }

// added 3 lines:
  if (process.ENV.FORCE_COLOR ==='always') {
    return true;
  }

  if (process.stdout && !process.stdout.isTTY) {
    return false;
  }
```

*Or just update the copy in the way that segrey says:* https://github.com/Marak/colors.js/issues/135#issuecomment-248930581

Thanks

Emilio

**Comment by mjmasn** [comment]
:+1:  This would be incredibly useful in combination with Winston + Meteor.js packages.

**Comment by icodeforlove** [comment]
this is a must have

**Comment by segrey** [comment]
Since `lib/system/supports-colors.js` is a copy of https://github.com/chalk/supports-color/blob/v3.1.2/index.js, it'd be better to just update the copy. That would fix this issue, because supports-color >= 2.0.0 [supports FORCE_COLOR](https://github.com/chalk/supports-color/commit/0ac45bd4dca5c1aa8b3551de6978c2000926a81d) environment variable.

**Comment by emilioplatzer** [comment]
I agree. Please do the update!

**Comment by DABH** [comment]
Done!  See `colors@next`!
