### ISSUE TITLE
Colors not working on iojs v3.3.0

### ISSUE THREAD

**Issue by mahdaen** [Marak/colors.js#139]
I'm not sure why, but after installing iojs v3.3.0 no more color on my terminal. :(

**Comment by Marak** [comment]
ok.

**Comment by zeeshanjan82** [comment]
+1

**Comment by zeeshanjan82** [comment]
Same is true with latest version of Node.js I am using v4.1

**Comment by Shershnev-AV** [comment]
It works for me if add bold style:
`colors.green('hello')` - don't work
`colors.green.bold('hello')` - works
nodejs v4.2.2/v5.0.0

**Comment by piranna** [comment]
On Node.js 4.3.1 I'm getting NaN as result instead of the correct string...

**Comment by DABH** [comment]
These all seem like very old versions so I'm going to close.  Please open an issue if you still have problems with latest node and `colors@next`.  Thanks!
