### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by mrkev** [Marak/colors.js#143]
The readme lists `reset` as a style, but it's actually not available. I'm guessing it's just outdated, and it is now meant to be `stripColors`

**Comment by DABH** [comment]
`reset` is defined here: https://github.com/Marak/colors.js/blob/master/lib/styles.js#L30 .  Seems to work for me, are you having any issues with using it?

**Comment by DABH** [comment]
Going to close this for now but feel free to re-open or make a new issue if there are problems (please test against `colors@next`, the latest version).  Thanks!

**Comment by mrkev** [comment]
Oh hmmm, maybe I just missed it? Sorry, my bad!
