### ISSUE TITLE
Not working with NetBeans IDE <---- Look at this :) It is easy to fix! (maybe ._.)

### ISSUE THREAD

**Issue by SCLeoX** [Marak/colors.js#148]
*This is my first time to write issue on github. If I made some mistake, please point them out directly.*

It is working with in CMD or other console on my computer but it is not working in NetBeans IDE's console.

It is caused by line **40-42** in [supports-colors.js](../blob/master/lib/system/supports-colors.js#L40L42).

    if (process.stdout && !process.stdout.isTTY) {
        return false;
    }

Some how, NetBeans IDE's console make this statement true and returned false. If I this `return false` to `return true`, it will work and shows color in the console.

I have no idea how to fix this problem.

**Comment by mothepro** [comment]
What OS are you using & version of Netbeans are you running?

**Comment by SCLeoX** [comment]
Netbeans IDE 8.1
Windows 10

**Comment by Irrelon** [comment]
Same for JetBrains IDE - OSX 10.11.2 - PHPStorm 10.0.3.

**Comment by Irrelon** [comment]
Created pull request to try and fix this is in a non-intrusive way by using environment variable "ALLOW_COLORS" to be set to true:

```js
process.env["ALLOW_COLORS"] = true;
```

Putting that at the top of your code before running any colored console logs will display nice colors in your IDE console output.

**Comment by SCLeoX** [comment]
I was solving this by using `--color`.
Adding a environment variable makes much more sense.
Thanks.
