### ISSUE TITLE
Offer to help maintain repo

### ISSUE THREAD

**Issue by marcuswestin** [Marak/colors.js#149]
Hi Marak,

I know it can be tricky to stay on top of github pull requests, especially over when you're very busy with other stuff for long periods of time. I recently managed to pull my head out of the sand and slog through 18 months of issues and PRs for github.com/marcuswestin/webviewjavascriptbridge and github.com/marcuswestin/store.js :)

If you would trust me to help maintain this library, then I would be up for helping out with the past ~9 months of PRs and issues this repo has. There's some pretty good stuff in some of them!

What do you say?

Cheers,
Marcus

**Comment by marcuswestin** [comment]
(I've also written the same basic functionality in the past - https://github.com/marcuswestin/node-color -, but instead of improving on that I'd much rather build on your (much more solid) foundation :)

**Comment by Marak** [comment]
@marcuswestin -

Good to hear from you again.

Based on your past work I'd be willing to accept your offer of help.

I've added you as a collaborator on the project. Please keep all your work in feature or release branches. Please do not commit to the `master` branch.

Unfortunately, my bandwidth to work on this project is very limited. I'm pretty tied up with pushing commits to other projects. I do use `colors` everyday, and it works for me.

I trust you to make the right decisions for managing the issues and pull requests. If you hit something you really feel requires my input let me know, but I'd prefer you try to figure it out on your own.

I'll keep my eye on the repo. When you are getting close to a new version I'll begin to the review the code-base.

Good luck and thank you.

**Comment by marcuswestin** [comment]
Great, sounds very reasonable. 




All I ask is that you make yourself available to move things along reasonably soon after I've made a chunk of progress. My incentive is to get meaningful improvements available via npm :) I promise to ask for your time only when there's a clear action list of things to go through.




Cheers, and thanks for the vote of confidence!

Marcus



-- while mobile

**Comment by Marak** [comment]
@marcuswestin -

I haven't seen any activity on the repo for two weeks.

Are you working on anything for colors right now?
