### ISSUE TITLE
zalgo.js takes 50% cpu time of my webpack builds

### ISSUE THREAD

**Issue by vjpr** [Marak/colors.js#151]
When I comment out everything in `zalgo.js` I am seeing my incremental build times halve.

I discovered this when CPU profiling my webpack build with `node-debug`.

![screen shot 2016-02-25 at 12 35 46 pm 2](https://cloud.githubusercontent.com/assets/281413/13308181/511cbdb0-dbc5-11e5-86d2-4a7a34569d91.png)

*Ignore the red rectangle...*

Using colors v1.1.2.

---

The webpack console shows this message when I comment out the file which might provide some clues:

```
WARNING in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
  resolve-url-loader cannot operate: CSS error
  colors.zalgo is not a function
  at String.zalgo (/Users/Vaughan/xxx/node_modules/colors/lib/extendStringPrototype.js:33:19)
```

Maybe resolve-url-loader is doing something messy.

**Comment by Marak** [comment]
Yes. Removing code will generally improve build times.

Not sure why you would be building a console color utility with webpack though.

**Comment by vjpr** [comment]
> Yes. Removing code will generally improve build times.

Obviously...

However, the build time goes from 14s to 7s. It is not related to the size of the code.

> Not sure why you would be building a console color utility with webpack though.

I'm not. This bug is related to `colors` being used during the compilation process in Node.js.

Many libraries depend on the unsafe version of colors.

---

It appears to be related to the `String.prototype` pollution but its not clear how. Here is the stack trace...

```
/Users/Vaughan/xxx/node_modules/colors/lib/custom/zalgo.js:2zalgo  
/Users/Vaughan/xxx/node_modules/colors/lib/extendStringPrototype.js:32(anonymous function) 
 /Users/Vaughan/xxx/node_modules/resolve-url-loader/node_modules/rework/node_modules/css/lib/parse/index.js:579addParent  
/Vaughan/xxx/node_modules/resolve-url-loader/node_modules/rework/node_modules/css/lib/parse/index.js:586(anonymous function) 
/Vaughan/xxx/node_modules/resolve-url-loader/node_modules/rework/node_modules/css/lib/parse/index.js:579addParent  
 /Users/Vaughan/xxx/node_modules/resolve-url-loader/node_modules/rework/node_modules/css/lib/parse/index.js:586(anonymous function) 
/Vaughan/xxx/node_modules/resolve-url-loader/node_modules/rework/node_modules/css/lib/parse/index.js:579
```

**Comment by Marak** [comment]
Yeah...if you require `colors` and do bad things to `String`...zalgo will be summoned.

:-)

**Comment by Marak** [comment]
> So anyone using a completely innocent for (var i in 'a string') will incur a huge performance penalty.


FYI. You should never iterate through a string using a for loop. You should `split` it into an array or use `substr`

**Comment by vjpr** [comment]
> Yeah...if you require colors and do bad things to String...zalgo will be summoned.

Was this the intent of zalgo? To identify bad usages of `String`? I didn't think about it until now, but it would actually be useful if `String.zalgo` called `console.log` :)

---

I think it should be documented on the `README` that if you use `require('colors')` and `for (var i in 'a string')` you will incur a huge performance penalty due to zalgo's random number usage.

**Comment by vjpr** [comment]
> FYI. You should never iterate through a string using a for loop. You should split it into an array or use substr

Yep...but you can't trust other library authors not too. Its super super dangerous.

**Comment by Marak** [comment]
> Yep...but you can't trust other library authors not too. Its super super dangerous.

What can I say? 

I'm not using any libraries in my dependency tree which are ever iterating over `String` using a for loop.

I know this due to the fact that `zalgo` doesn't appear anywhere on my terminal or in any of my strings.

Observe:

```js

require('colors');

console.log("foo".red)

var s = "foo bar";
for (var x in s) {
  console.log(s[x])
}
```

<img src="http://i.imgur.com/dldEq5G.png"></img>

**Comment by vjpr** [comment]
> I know this due to the fact that zalgo doesn't appear anywhere on my terminal or in any of my strings.

But you have to use `console.log`, which the authors of the `css` library weren't.

The simple fix would be to add a getter, that when invoked will call `console.warn('You are iterating over a String's properties. You will incur a performance penalty becase require('colors') has been used. See an-url-linking-to-readme for details')`

**Comment by Marak** [comment]
It's not as simple as you think.

**Comment by vjpr** [comment]
> It's not as simple as you think.

Why not? Otherwise, there are huge potential slow-downs lurking out there if someone has only called `require('colors')`.

Maybe I am missing something?

**Comment by Marak** [comment]
Sorry. Your edits weren't propagating to my email client.

I've only been seeing half the conversation.

Yes, we could probably add a warning message using `console` if someone
accidentally triggers a prototyped string method.


On Wed, Feb 24, 2016 at 11:24 PM, Vaughan Rouesnel <notifications@github.com

**Comment by vjpr** [comment]
> Yes, we could probably add a warning message using `console` if someone
accidentally triggers a prototyped string method.

Cool!

There was an existing issue about this already too: https://github.com/Marak/colors.js/issues/88

**Comment by Marak** [comment]
There have been a lot of issues opened about `String.prototype` usage.

I like having the short-hand syntax for `console.log` output, others disagree.
