### ISSUE TITLE
eslint "no-unused-vars" warning

### ISSUE THREAD

**Issue by mpint** [Marak/colors.js#161]
```
import colors from 'colors';
console.log('throws eslint warning'.yellow);
```

Is there any workaround to avoid this eslint warning:

`!  2:8  'colors' is defined but never used  no-unused-vars`

thanks!

**Comment by icodeforlove** [comment]
yes, you can do

```
import 'colors';
```

since colors actually modifies the `String.prototype`

**Comment by DABH** [comment]
Sounds like this is resolved -- ^thanks!
