### ISSUE TITLE
ES2015 template strings don't work in "safe" mode

### ISSUE THREAD

**Issue by markplewis** [Marak/colors.js#178]
I can't seem to make Colors work with ES2015 template literals in "safe" mode. The following example outputs white text in my terminal:

```
const colors = require("colors/safe");

console.log(`
CPU: ${colors.red('90%')}
RAM: ${colors.green('40%')}
DISK: ${colors.yellow('70%')}
`);
```

![screen shot 2016-12-29 at 10 53 43 am](https://cloud.githubusercontent.com/assets/2489555/21548482/936ce6e4-cdba-11e6-9671-8d08a03655c2.png)

Using raw color codes, however, works as expected:

```
console.log('\x1b[36m%s\x1b[0m', "Hello"); // cyan
```

I tested this in both the Mac OS Terminal app and in iTerm2.

I'm having [a similar problem with Chalk](https://github.com/chalk/chalk/issues/138).

**Comment by markplewis** [comment]
**UPDATE:** The problem with Chalk was that it wasn't automatically detecting color support, so I had to forcibly enable it, like this:

```
const ch = require("chalk");
const chalk = new ch.constructor({enabled: true});
```

I imagine I'm encountering the same problem with Colors. Does Colors provide a mechanism to forcibly enable support like this, in cases where the auto-detection has failed for some reason?

**Comment by DABH** [comment]
There are indeed ways to force colors to be enabled, see https://github.com/Marak/colors.js/blob/master/lib/system/supports-colors.js (same underlying mechanisms as chalk); you can set env vars like FORCE_COLOR, pass flags like --color, or set `colors.enabled = true;` (https://github.com/Marak/colors.js/blob/master/lib/colors.js).

However, there do seem to be some issues with template strings, so I'm going to close this in favor of #167 where hopefully we can get to the bottom of what's going on there.  I'd love to get colors working fully with template strings.  Thanks!
