### ISSUE TITLE
Themes can have multiple attributes - but not in safe mode

### ISSUE THREAD

**Issue by adam-nielsen** [Marak/colors.js#180]
The end of the `README` says you can do this:
```javascript
var colors = require('colors');

colors.setTheme({
  custom: ['red', 'underline']
});

console.log('test'.custom);
```
However if you then try to use this in safe mode, it doesn't work:
```javascript
console.log(colors.custom('test'));  // TypeError: colors.custom is not a function
```
The reason I am reporting this as a bug is that it works if you only specify one attribute:
```javascript
colors.setTheme({
  custom: 'red'
});
console.log(colors.custom('test'));  // all good
```
The error only happens when multiple attributes are supplied as an array, when using safe mode.

**Comment by DABH** [comment]
Interesting!  We'd welcome a PR for this...

**Comment by DABH** [comment]
Big thanks to @zucher , this should be fixed at last.  We will be pushing a new release of colors soon that includes this fix.  Thanks again for bringing this bug to our attention.

**Comment by mike-lischke** [comment]
Has this code been released actually? Today I update to 1.3.3 and I get odd behavior with multiple attributes. Here's what I use:

```js
function prepareConsoleColors() {
    const colors = require("colors");

    colors.setTheme({
        heading: ['bold', 'underline'],
        title: 'underline',
        success: ['green'],
        failure: ['bold', 'red'],
        excluded: ['grey'],
        pending: ['blue']
    });
}
```
With:

```js
var heading = "Testing Heading".heading;
console.info(heading + "\n");
```

I get:

![bildschirmfoto 2019-01-09 um 14 43 59](https://user-images.githubusercontent.com/2398704/50903103-0f9c0100-141d-11e9-9063-eb1900696bf3.png)

Note also the `success` strings, which should actually have "√" as text, not the theme name.

**Comment by DABH** [comment]
Can you provide full code sample? (With success stuff) I can take a look

**Comment by mike-lischke** [comment]
Hmm, you should easily be able to reproduce with what I posted already, but here we go:

```js
"use strict"

prepareConsoleColors();
console.log("Test Output".success);

function prepareConsoleColors() {
    const colors = require("colors"); // Will hook into String.

    colors.setTheme({
        heading: ['bold', 'underline'],
        title: 'underline',
        success: ['green'],
        failure: ['bold', 'red'],
        excluded: ['grey'],
        pending: ['blue']
    });
}
```

That prints `success`, not `Test Output` as it should.
