### ISSUE TITLE
docs correction: Usage section

### ISSUE THREAD

**Issue by lmj0011** [Marak/colors.js#181]
https://github.com/Marak/colors.js#usage

for the `The super nifty way`

```js
var colors = require('colors');`
``` 
should be

```js
 require('colors');
```

es6 equivalent: 
```js
import colors from 'colors';` 
```

would be 

```js
import 'colors';
```

**Comment by DABH** [comment]
In this case you're right that `require('colors');` is sufficient, but one might want to add something like `colors.setTheme(...)` which would then necessitate the named import.  So I feel like it's probably fine to leave this doc as-is for the time being.  Thank you!
