### ISSUE TITLE
 ReferenceError: Can't find variable: process

### ISSUE THREAD

**Issue by jpca999** [Marak/colors.js#187]
whenever i try to run it, it says, 

root@d3c546b5a574:/var/www/simple_casper# casperjs example.js
ReferenceError: Can't find variable: process

 /var/www/simple_casper/node_modules/colors/lib/system/supports-colors.js:26
  /var/www/simple_casper/node_modules/colors/lib/system/supports-colors.js:61

![image](https://cloud.githubusercontent.com/assets/1026325/24075429/d74c5852-0bf1-11e7-8c6f-52783993e295.png)

**Comment by weichenghsu** [comment]
any update? I got this exception as well

**Comment by jpca999** [comment]
Use some other library like chalk.js

**Comment by DABH** [comment]
I'm going to close this as a duplicate for now; there are a few other issues discussing problems with supports-colors.js.  We will be updating that file in an upcoming release, and if there's still any issues like that after the next release, definitely reopen this issue or open a new one.  Thanks!
