### ISSUE TITLE
Color library is not working in gitbash

### ISSUE THREAD

**Issue by walifaizy** [Marak/colors.js#191]
Node version: 6.10.0

npm version: 3.9.5

Operating system: windows 10

Command line used: Git bash

Steps to reproduce:
I am trying to make text(Starting App in Deve mode) in green color but it is not happening, can you please preview my project github link 
[https://github.com/walifaizy/react-redux-library](url)
![screenshot 86](https://cloud.githubusercontent.com/assets/17082693/25072682/8bbad1aa-22e6-11e7-8787-1de075b5af30.png)

**Comment by wzup** [comment]
100% true. 
Does not work at all.

**Comment by wzup** [comment]
A workaround https://github.com/Marak/colors.js/issues/196#issuecomment-302943622

> Setting `process.stdout.isTTY = true;` before importing colors works

```
process.stdout.isTTY = true;
var colors = require('colors');
```

**Comment by DABH** [comment]
Does this work now using `colors@next`?  I believe this should have been fixed, without having to use the workaround.

**Comment by DABH** [comment]
Marking this as closed due to lack of activity.  Thanks!
