### ISSUE TITLE
undefined is not an object (evaluating 'argv.indexOf')

### ISSUE THREAD

**Issue by ElSadeq** [Marak/colors.js#194]
I'm trying to use colors in my logs but when I try to require ('colors') to my app I get this error... I'm using it with react native, what could be the problem?

**Comment by xahon** [comment]
have same problem too

**Comment by jniac** [comment]
same problem here

**Comment by DABH** [comment]
This will be fixed with #172 -- closing this for now, feel free to follow the discussion on that PR.  Thanks!!
