### ISSUE TITLE
Doesn't work in Git Bash

### ISSUE THREAD

**Issue by wzup** [Marak/colors.js#196]
Doesn't work in this Git Bash terminal on Windows 10 64bit

![mintty 2017-05-21 23 07 23](https://cloud.githubusercontent.com/assets/3880497/26285082/bee5ab4a-3e7a-11e7-8df6-e9a4dd83f029.png)

Neither option works. Just nothing is colored.
```
const colors = require('colors');

console.log('hello'.green);
console.log(colors.green('hello'));
```

**Comment by wzup** [comment]
Found a work-around here https://github.com/Marak/colors.js/issues/136#issuecomment-123792950

> Setting `process.stdout.isTTY = true;` before importing colors works

**Comment by DABH** [comment]
How does it work now with `colors@next`?

**Comment by wbern** [comment]
I'd just like to drop a note that installing colors@1.2.0-rc0 (aka `next` as of current writing) fixes the issue I had using git bash.

**Comment by DABH** [comment]
Sweet!  Thanks for the report!  I’m marking this as closed, I think we solved this issue.
