### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by abetomo** [Marak/colors.js#197]
@Marak Is it no longer maintenance?
If you are not doing maintenance, it is a very favorite project so I would like to maintain it.

**Comment by faceyspacey** [comment]
@abetomo I don't suppose you know why this package stopped working on Travis? I'm doing the `String.prototype` modifying method.

**Comment by faceyspacey** [comment]
found a new Travis issue for it:

https://github.com/travis-ci/travis-ci/issues/7967

it just started happening.

**Comment by fujio0000** [comment]
@Marak 
Are you currently performing maintenance?
Are you planning to release a new version?

**Comment by Marak** [comment]
Probably sometime.

It still works for me.

There are also many other packages for doing this.

**Comment by abetomo** [comment]
Thank you for answering!
