### ISSUE TITLE
.setTheme() is not working

### ISSUE THREAD

**Issue by MickL** [Marak/colors.js#198]
```
const colors = require('colors');

colors.setTheme({
	success: '#3c763d',
	info: '#31708f',
	warning: '#8a6d3b',
	error: '#a94442'
});

console.log('hello there'.info);
```

throws:

```
colors[theme[prop]] is not a function
```

While default colors are working: `console.log('hello there'.yellow);`

**Comment by SUpermin6u** [comment]
only support these props:
{
  silly: 'rainbow',
  input: 'grey',
  verbose: 'cyan',
  prompt: 'grey',
  info: 'green',
  data: 'grey',
  help: 'cyan',
  warn: 'yellow',
  debug: 'blue',
  error: 'red'
}

**Comment by GlitchMasta47** [comment]
Same issue here, I have included the stack trace below in case it is needed.
```
<project folder>\node_modules\colors\lib\extendStringPrototype.js:89
              ret = colors[theme[prop][t]](ret);
                                          ^

TypeError: colors[theme[prop][t]] is not a function
    at String.info (<project folder>\node_modules\colors\lib\extendStringPrototype.js:89:43)
    at Object.<anonymous> (<project folder>\index.js:14:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by GlitchMasta47** [comment]
Screenshot of the source code around the area it produced the error
![image](https://user-images.githubusercontent.com/17860556/34597772-7fea6254-f1ae-11e7-80fd-abc36ec21af3.png)

**Comment by steveblue** [comment]
Same issue here: TypeError: colors.verbose is not a function

**Comment by DABH** [comment]
If I use a built-in color name like `green` in OP's example, everything works fine.  So I believe this is not a bug with defining a custom theme; rather, it's just that colors.js doesn't support custom hex colors like that right now.  That is one of the big features we have planned for an upcoming release though.

Please feel free to re-open if it seems like I'm missing something, thanks!
