### ISSUE TITLE
Keep colors when not a TTY

### ISSUE THREAD

**Issue by trufae** [Marak/colors.js#199]
I want to use | less -R with a program im using colors.js, by reading the checks in index.js there's no way to override this behaviour because the isTTY chk is done before the env var check, so the user have no choice to scroll with less.

Also, using colorized output of colors.js with less -R results in only the first line colorized, because the ansi escape codes should be done on every single line, instead of the whole string. I have workarounded this in my code, but will be good if colors.js could handle that too, this is probably a separate issue

**Comment by beether** [comment]
I spent two hours trying to figure out why I couldn't capture color in a node process I was spawning.  First of all, node is crap. You can use `spawn` with `{stdio: 'inherit'}` to preserve colors, but then you have no way of capturing the the actual f***ing output. It goes straight to stdout with no way to intercept it.

Secondly, it's astonishing that this library would forcibly disable itself with no way to prevent it from happening.

I've ported everything to `chalk` and am not looking back.

**Comment by jaredallard** [comment]
https://github.com/Marak/colors.js/blob/cc857f297748633785b2bcf555f226930c8dee4d/lib/system/supports-colors.js#L39

Have you tried `FORCE_COLOR=1`?

**Comment by givehug** [comment]
`FORCE_COLOR` works if I define colors manually eg `console.log('\x1b[36m', 'sometext' ,'\x1b[0m');`
But not with `colors` package.
FYI colors from mocha output are preserved, not sure what they use.

**Comment by DABH** [comment]
We have fixed the multiline coloring issue OP mentioned, and that FORCE_COLOR check should be more robust too.  Sounds like things are working for people (woo!), feel free to open another issue if you run into any specific examples that aren't working.  Thanks!
