### ISSUE TITLE
See colors with tail-f

### ISSUE THREAD

**Issue by djcaesar9114** [Marak/colors.js#207]
Hello,
I use your package which works fine when I check the log directly in the console. But when I go on production, I put my logs in a file, and `tail -f` this file when I want to check what happens live. When I do this, I can't see colors.
Is there a way to make me see colors when I write in a file?
Thanks!

**Comment by instalab** [comment]
How do you even expect to write colours to plain text file?

**Comment by djcaesar9114** [comment]
That is indeed a good question. Sometimes I want to go back in time and slap myself in the face really hard.
