### ISSUE TITLE
Allow to enable/disable colors when colors.js is imported as an ES6 module

### ISSUE THREAD

**Issue by bcaudan** [Marak/colors.js#221]
I am using typescript and this code:
```typescript
import * as colors from "colors"; 

colors.enabled = true;
```
give me this error:

    error TS2540: Cannot assign to 'enabled' because it is a constant or a read-only property    

As explained in https://github.com/Microsoft/TypeScript/issues/6751, there are workarounds but the right way could be to expose methods to enable/disable colors.

If it sounds relevant to you, I would be glad to help.

**Comment by DABH** [comment]
This will be included in the next release.  Thanks again!
