### ISSUE TITLE
Allow --no-colors through ENV instead of just CLI args

### ISSUE THREAD

**Issue by mearns** [Marak/colors.js#240]
It would be great to support disabling of colors, as currently done with the --no-colors, through an environment variable. For instance, if an environment variable named NO_COLORS is defined, disable colors.

**Comment by DABH** [comment]
Sure, we have `FORCE_COLORS` right now for forcing colors to be enabled, we could add `FORCE_NO_COLORS` (I would be happy to review a PR).  Just figure out what should happen if both FORCE_COLORS and FORCE_NO_COLORS were set in a user's environment :)

**Comment by DABH** [comment]
merged #21!
