### ISSUE TITLE
Cannot read property 'bgBlue' of undefined

### ISSUE THREAD

**Issue by SpiritUrban** [Marak/colors.js#244]
...\node_modules\colors\lib\extendStringPrototype.js:79
            tmp = tmp[theme[prop][t]];
                     ^

TypeError: Cannot read property 'bgBlue' of undefined

**Comment by SpiritUrban** [comment]
"colors": "^1.3.2",

**Comment by SpiritUrban** [comment]
For resolving this problem. I use "colors": "1.3.0",

**Comment by DABH** [comment]
Can you please provide a code sample that triggered that error?

**Comment by SpiritUrban** [comment]
module.exports = function (app) {


    var colors = require('colors')

    colors.setTheme({
        silly: 'rainbow',
        input: 'grey',
        verbose: 'cyan',
        prompt: 'grey',
        info: 'green',
        data: 'grey',
        help: 'cyan',
        warn: 'yellow',
        debug: 'blue',
        error: 'red',
        test: ['yellow'],
        custom: ['red', 'underline', 'america', 'bgBlue']
    })

**Comment by DABH** [comment]
This was a frustrating one to fix!  Check out v1.3.3 though, I think your example runs.  Whew.

Note that the expected behavior from colors still might not be what you want because nesting of ASCII color codes is very finicky (not a problem with colors, just the nature of how color codes work).
