### ISSUE TITLE
lib/.colors.js.swp file is present in the published npm package

### ISSUE THREAD

**Issue by harryi3t** [Marak/colors.js#248]
Looks like this swap file `.colors.js.swp` is present whenever we install this package at `./node_modules/colors/lib`. Although this file is not present in the Github source code.

The first list is from the source code, 2nd is from the installed package in node_modules
![image](https://user-images.githubusercontent.com/5207331/49526114-28247300-f8d5-11e8-9571-4e9d5ebce073.png)

**Comment by DABH** [comment]
Fixed in v1.3.3!
