### ISSUE TITLE
Broken functionality?

### ISSUE THREAD

**Issue by mk360** [Marak/colors.js#275]
For some reason even I am not sure of, attempting to use
![Capture d’écran du 2020-07-26 00-07-46](https://user-images.githubusercontent.com/36678834/88466359-33764900-ced4-11ea-810a-e1c6749e6a15.png)
yields an error stating that `Colors.green` is not a function, even though it was working before (before as in a week ago), and the TS type is telling me that what I'm doing is right. I might be wrong, I might've missed something, but I'm really not sure what it is. This package is a core tool in my project and it would be really bad to remove it.

**Comment by mikeerickson** [comment]
How are you importing the module?

**Comment by mk360** [comment]
Never mind, tried the default import way (instead of `import * as whatever from "colors"` and everything seems to work. My bad, should've checked before opening this issue.
