### ISSUE TITLE
Recommended method to view logs

### ISSUE THREAD

**Issue by Slurpgoose** [Marak/colors.js#276]
Hi, thank you for creating and maintaining this awesome library.

**is there a recommended method to view logs that use colors?**

I am using pm2 to generate logs and the output of `less errors.log`

> 2020-11-08T22:21:05: ESC[31mmissing ticker for OMG-BTC, will resubscribeESC[39m

The best solution I came up was removing color codes using sed and creating a new file to read using less 
`cat errors.log | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | tee errors-copy.log | less errors-copy.log`

My preferred solution would be to parse the color codes instead of removing them.

thanks.

**Comment by Gerrit0** [comment]
`less -R` will process color escapes
