### ISSUE TITLE
v1.4.2 is broken

### ISSUE THREAD

**Issue by dhilt** [Marak/colors.js#289]
It was released 1 hour ago and broke my tests in the following nice (not) way:

<img width="568" alt="Screenshot 2022-01-09 at 23 49 28" src="https://user-images.githubusercontent.com/4365660/148700265-8b0063f7-28dd-4dbe-bb0b-892a6105b186.png">

I fixed it in my lib by reverting package-lock.json: https://github.com/dhilt/ngx-ui-scroll/pull/300/commits/dd782fce90217c730419b32c82e86af529752f3a (BTW it is suggested to downgrade to 1.4.0, thanks to @lirantal, so here's [another downgrade commit](https://github.com/dhilt/ngx-ui-scroll/pull/300/commits/56c7bebdd4363477b0f9746b35e451debb1552b5))

I suppose it might relate to destruction of the Faker.js project (5 days ago): https://github.com/Marak/faker.js

**Comment by Hamahmi** [comment]
It is, check this commit https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by floscher** [comment]
See #285

**Comment by lirantal** [comment]
@dhilt please revert back to using `1.4.0` if you can to mitigate the issue.
Versions `1.4.1` and `1.4.2` would both introduce a denial of service upon usage.

**Comment by dhilt** [comment]
@lirantal Thanks, will do!

**Comment by Apollon77** [comment]
@Marak Can you please kill 1.4.1 and 1.4.2 from npm and adjust latest back to 1.4.0 please ... It is breaking a lot!

**Comment by pxseu** [comment]
> @Marak Can you please kill 1.4.1 and 1.4.2 from npm and adjust latest back to 1.4.0 please ... It is breaking a lot!

That's.... the point of why he has done that

**Comment by dustinlw1987** [comment]
Marak should NOT be trusted as a developer! Especially after doing this unilaterally without notification.

**Comment by DABH** [comment]
Please consider closing this issue so that people will go to #285 instead -- trying to keep solutions and updates in one place.  Thanks.

**Comment by dustinlw1987** [comment]
> > @Marak Can you please kill 1.4.1 and 1.4.2 from npm and adjust latest back to 1.4.0 please ... It is breaking a lot!
> 
> That's.... the point of why he has done that

There is absolutely NO REASON to fuck over people this way! That's how you burn bridges and have people not trust you as an developer.

**Comment by pxseu** [comment]
I'm not saying what he has done was right but in my opinion he doesn't have
to notify someone with a change in his software, you're free to fork it and
all

**Comment by dustinlw1987** [comment]
Sure, and that is EXACTLY what is happening. Marak is being cut out and deleted as nobody trusts him now.

**Comment by Apollon77** [comment]
In my eyes there are two sides right now:
1.) The present and how to fix the real issue ... ideally supporting him that he hopefully reverts latest on npm to 1.4.0
2.) Future: Then the affected libraries can think about movingg away or whatever

I'm interested rigt now in Point 1 ...

**Comment by shayneoneill** [comment]
"ideally supporting him"

Yeah, no. That would be deeply irresponsible. Not after this. Rewarding this sort of malicious behavior just leads to more of it.

**Comment by DevXiaolan** [comment]
> 

Did it so

**Comment by rsadr0pyz** [comment]
**npx marak-free**

**Comment by karikera** [comment]
v1.4.1 is also broken
v1.4.0 is working

**Comment by euberdeveloper** [comment]
Hi, in case the author will not maintain this project or fix this, I made a fork that restores the normal behaviour. I am not sure if I will maintain this package, but just in case the problem will not be solved and you don't want to be scared when running `npm update`...

https://github.com/euberdeveloper/colors.js

In any case I could also suggest passing to the chalk package, which is very good and has a serious and reliable author

**Comment by RIAEvangelist** [comment]
Here is an alternative, optionally, you could easily write your own module :

`nozaki-colors` https://github.com/RIAEvangelist/nozaki-colors

**Comment by TechStudent10** [comment]
@npm revert it to a working version.

**Comment by serenecloud** [comment]
@TechStudent11 looks like @npm have indeed reverted https://www.npmjs.com/package/colors to 1.4.0

**Comment by TechStudent10** [comment]
> @TechStudent11 looks like @npm have indeed reverted https://www.npmjs.com/package/colors to 1.4.0

good

**Comment by dhilt** [comment]
Great, closing this as npm has removed broken versions and reverted to 1.4.0
