### ISSUE TITLE
Library has been corrupted

### ISSUE THREAD

**Issue by jvissers** [Marak/colors.js#297]
This is no longer working

**Comment by brolnickij** [comment]
realy?!?!?!

![image](https://user-images.githubusercontent.com/10180323/148773192-bb626676-7d70-4294-8468-22fe2bf533a5.png)

**Comment by karikera** [comment]
Duplicate of #289

**Comment by jvissers** [comment]
I just wanted to be as funny as the original author that originally wrecked the day **on purpose** for a number of people.

![really](https://user-images.githubusercontent.com/2955276/148808994-8edb9d02-4308-4adc-924d-314885dda331.jpeg)

**Comment by Awilum** [comment]
OMG. Really ?

**Comment by jvissers** [comment]
Duplicate
