### ISSUE TITLE
Liberty, yourself?!

### ISSUE THREAD

**Issue by rilysh** [Marak/colors.js#323]
Can you clearly answer what's this? I getting no idea, confused that what're you trying to do...
https://github.com/Marak/colors.js/blob/6bc50e79eeaa1d87369bb3e7e608ebed18c5cf26/lib/custom/american.js#L2

**Comment by prietales** [comment]
Please, stop asking if you want to stay alive, don't you realize that this is all a very murky matter?

**Comment by rilysh** [comment]
> Please, stop asking if you want to stay alive, don't you realize that this is all a very murky matter?

"If you want to stay alive"
Are you trying to say that I'll die if I ask? Even I saw this yesterday when I've mentioned this issue, also I asked to author  not you.

**Comment by prietales** [comment]
The author is dead.

**Comment by DanielRuf** [comment]
> The author is dead.

Didn't he comment today? Any verifiable evidence or is this some rumour?

@prietales doesn't seem to be true. See https://github.com/Marak/colors.js/issues/285#issuecomment-1013235596

**Comment by DanielRuf** [comment]
@prietales doesn't look to be true. See https://github.com/Marak/colors.js/issues/285#issuecomment-1013235596

**Comment by prietales** [comment]
> DanielRuf


They are just scheduled messages.

**Comment by DanielRuf** [comment]
@prietales you didn't come up with any real evidence. Marak also posted on Twitter. This rumour does not help anyone.

**Comment by DanielRuf** [comment]
Would be new to me that you can schedule messages on GitHub. Also in the original topic he replied to another comment.

https://github.com/Marak/colors.js/issues/285#issuecomment-1013270893

Besides the nonsense he writes, there is no real evidence about a death.

**Comment by rilysh** [comment]
I'm out of ideas, so I just proposed that it can be two matter

If it's true https://github.com/Marak/colors.js/issues/323#issuecomment-1013039521 that author is no longer so it's someone else who committed on GitHub and Twitter
Else author is still alive we're just out of evidence.

**Comment by prietales** [comment]
https://docs.github.com/en/rest/reference/pulls

**Comment by DanielRuf** [comment]
@prietales pulls are not comments. Pulls are pull requests. And you still did not provide any real evidence. So this proves literally nothing. Don't believe everything that you read somewhere =)

**Comment by ghost** [comment]
![Maraaak](https://user-images.githubusercontent.com/97804104/149634062-f36195dd-d421-47a9-a720-69983437d5bc.png)

**Comment by prietales** [comment]
Wait

**Comment by prietales** [comment]
POST https://github.com/Marak/colors.js/issue_comments

content-type: multipart/form-data;
Content-Disposition: form-data; name="issue_comment[body]"

HELLO COMMENT!

**Comment by RIAEvangelist** [comment]
cyberbullying is not ok.

**Comment by prietales** [comment]
> cyberbullying is not ok.

Please stop cyberbullying us and in any case stop misusing the word cyberbullying and applying it to anything.

**Comment by rilysh** [comment]
> POST https://github.com/Marak/colors.js/issue_comments
> 
> content-type: multipart/form-data; Content-Disposition: form-data; name="issue_comment[body]"
> 
> HELLO COMMENT!

Why did you post headers "Content-Type" and etc?

**Comment by dragonfirefox** [comment]
> ![Maraaak](https://user-images.githubusercontent.com/97804104/149634062-f36195dd-d421-47a9-a720-69983437d5bc.png)

Legends never die
When the world is calling you
Can you hear them screaming out your name?
Legends never die
They become a part of you
Every time you bleed for reaching greatness
Relentless you survive
They never lose hope when everything's cold
And the fighting's near
It's deep in their bones, they'll run into smoke
When the fire is fierce
Oh, pick yourself up, 'cause
Legends never die
When the world is calling you (the world is calling you)
Can you hear them screaming out your name?
Legends never die
They become a part of you (they become a part of you)
Every time you bleed for reaching greatness
Legends never die
They're written down in eternity
But you'll never see the price it costs
Scars collected all their lives
When everything's lost, they pick up their hearts
And avenge defeat
Before it all starts, they suffer through harm
Just to touch a dream
Oh, pick yourself up, 'cause
Legends never die
When the world is calling you (when the world is calling you)
Can you hear them screaming out your name?
Legends never die
They become a part of you (they become a part of you)
Every time you bleed for reaching greatness
Legends never die
When the world is calling out your name
Begging you to fight
Pick yourself up once more
Pick yourself up, 'cause
Legends never die
When the world is calling you (the world is calling you)
Can you hear them screaming out your name?
Legends never die
They become a part of you (they become a part of you)
Every time you bleed for reaching greatness
Legends never die

**Comment by prietales** [comment]
Hi! This is a scheduled comment.

**Comment by RIAEvangelist** [comment]
> > POST https://github.com/Marak/colors.js/issue_comments
> > content-type: multipart/form-data; Content-Disposition: form-data; name="issue_comment[body]"
> > HELLO COMMENT!
> 
> Why did you post headers "Content-Type" and etc?

that's what happens when you reply from an email notification, I think he is trying to emulate that.

**Comment by RIAEvangelist** [comment]
> > cyberbullying is not ok.
> 
> Please stop cyberbullying us and in any case stop misusing the word cyberbullying and applying it to anything.

@prietales the comment above with the large image in this thread is clearly bullying, also, your comment in one of the threads, maybe this one, if it was deleted, where you encoded abusive name-calling in binary, is bullying. Calling people names like that, especially calling them profane names, is cyberbullying.

I'll not back down from this stance as this sort of behavior can not be left unopposed. It is wrong and if left unopposed it will appear as if it's ok to treat others that way.  I for one do not care if you think it's ok, or your right, to abuse others publicly. It is only your right to do it if you want to face the repercussions. Some users have already been banned from Github for this.

**Comment by prietales** [comment]
> > > cyberbullying is not ok.
> > 
> > 
> > Please stop cyberbullying us and in any case stop misusing the word cyberbullying and applying it to anything.
> 
> @prietales the comment above with the large image in this thread is clearly bullying, also, your comment in one of the threads, maybe this one, if it was deleted, where you encoded abusive name-calling in binary, is bullying. Calling people names like that, especially calling them profane names, is cyberbullying.
> 
> I'll not back down from this stance as this sort of behavior can not be left unopposed. It is wrong and if left unopposed it will appear as if it's ok to treat others that way. I for one do not care if you think it's ok, or your right, to abuse others publicly. It is only your right to do it if you want to face the repercussions. Some users have already been banned from Github for this.

stop threatening me.

**Comment by RIAEvangelist** [comment]
I am not making threats I am standing against your behavior and making it clear that it is not ok. Our behavior often has real world consequences, like being banned. If you find that idea threatening it shows that you feel something you have done may warrant such consequences.

You would not find this threatening if you didn't know you did something wrong and were trying to cover it up by twisting yourself into being the victim. Accepting responsibility and not behaving this way in the future will alleviate you from such feelings in the future. It is never too late to consider the responsibility you have for your own actions. This is a simple part of maturing and you should take this as an opportunity for growth rather than one to try and escape.

**Comment by prietales** [comment]
😴

**Comment by rilysh** [comment]
> Hi! This is a scheduled comment.

How? Does he have AI based system or I've never heart GitHub scheduled comment , sorry...

**Comment by prietales** [comment]
> > Hi! This is a scheduled comment.
> 
> How? Does he have AI based system or I've never heart GitHub scheduled comment , sorry...

Its very simple to post a comment without any official API.

**Comment by RIAEvangelist** [comment]
Just because someone makes something look a certain way doesn't mean it is.

Otherwise he could share the code that does it. At the moment though to me
there is not much certainty in any of the posts.

**Comment by rilysh** [comment]
@Marak
Please, stop now.
https://audio-video.gnu.org/video/TEDxGE2014_Stallman05_LQ.webm

**Comment by RIAEvangelist** [comment]
> @Marak
> Please, stop now.
> https://audio-video.gnu.org/video/TEDxGE2014_Stallman05_LQ.webm

Wow, that's a REALLY good video.

**Comment by d3r1n** [comment]
Everyone is trying to make @Marak end this propaganda/action but why not just... move on? Depending on a thing this much is wrong. You can write your own version of it or just write the part you're actually using. If you are incapable of doing that then you can't call yourself a developer.

**Comment by rilysh** [comment]
> Everyone is trying to make @Marak end this propaganda/action but why not just... move on? Depending on a thing this much is wrong. You can write your own version of it or just write the part you're actually using. If you are incapable of doing that then you can't call yourself a developer.

That's not a point, to judge. The main topic was why he is doing this at all, not talking about creating own module or editing it. Pretty much everyone is capable to do itself.

**Comment by wory48** [comment]
Welp, this topic was 12 days ago shit, and some random people just join to an open issue page and still talk about same thing, try to write something for their growth, not useful at all.

**Comment by RIAEvangelist** [comment]
It took me less than a couple hours to create [my own version](https://github.com/RIAEvangelist/nozaki-colors)
