### ISSUE TITLE
Faker.js problem

### ISSUE THREAD

**Issue by toviszsolt** [Marak/colors.js#330]
@Marak Something wrong with the faker.js repo, please check ignored files... NPM package also.

**Comment by rilysh** [comment]
Hey toviszsolt! Faker.js new repo https://github.com/faker-js/faker
There's a big issue happens to Marak, you can understand by seeing other issue titles.

For info what happens to real faker js some of here https://github.com/faker-js/faker#faq---what-happened-to-the-original-fakerjs

**Comment by toviszsolt** [comment]
Said. Thanks.
