### ISSUE TITLE
Use TRUE Open Source ANSI Styling Lib - ANSIS

### ISSUE THREAD

**Issue by webdiscus** [Marak/colors.js#333]
Color styling of text for ANSI terminals - [ansis](https://github.com/webdiscus/ansis)

P.S. Sorry for this SPAM, but is really good lib.

**Comment by rilysh** [comment]
> Color styling of text for ANSI terminals - [ansis](https://github.com/webdiscus/ansis)
> 
> P.S. Sorry for this SPAM, but is really good lib.

Eh, why you're promoting your library to an issue page?
