### ISSUE TITLE
Add multi-mode styling

### ISSUE THREAD

**Issue by Marak** [Marak/colors.js#4]
We should be able to switch colors into one of three modes:

The first mode will operate as colors.js works now. It will apply ANSI escape codes to the string.

The second will return an object literal describing the object which was sent to it, i.e. 'foo'.yellow returns { string: 'foo', styling: ['yellow'] }

The third mode ( as suggested by @TooTallNate ) will output colored html markup for the browser.

**Comment by 360disrupt** [comment]
I do get these ansi escapers in my log files on exceptions. is there an option to strip them, it makes the log very unreadable:

## Code
```
winston.handleExceptions(new winston.transports.File({ filename: 'logs/uncaughtExceptions.log' }))
````

e.g.
```
...
\u001b[0m\u001b[97m\u001b[41mError\u001b[0m\u001b[90m:\u001b[0m\u001b[37m \u001b[0m\u001b[97mlisten EACCES 0.0.0.0:80\u001b[0m","\u001b[0m  \u001b[0m","\u001b[0m  \u001b[0m\u001b[90m-\u001b[0m \u001b[0m\u001b[93mutil.js\u001b[0m\u001b[90m:\u001b[0m\u001b[93m856\u001b[0m\u001b[37m \u001b[0m\u001b[37mObject.exports._errnoException\u001b[0m","\u001b[0m  \u001b[0m  \u001b[0m\u001b[90mutil.js:856:11\u001b[0m","\u001b[0m  \u001b[0m","\u001b[0m  \u001b[0m\u001b[90m-\u001b[0m \u001b[0m\u001b[93mutil.js\u001b[0m\u001b[90m:\u001b[0m\u001b[
...
```
