### ISSUE TITLE
Allow themes to have combinations

### ISSUE THREAD

**Issue by danielb2** [Marak/colors.js#72]
underline + color, for example.

How does one do bold red?

**Comment by konsumer** [comment]
You can do this with this module, too:
```javascript
console.log('Listening on ' + colors.underline(colors.blue('http://0.0.0.0:' + port))  );
```

but the OP is asking for it in themes, which I would also like:
```
colors.setTheme({
  link: 'underline.blue'
});
console.log('Listening on ' + colors.link('http://0.0.0.0:' + port)  );
```

**Comment by konsumer** [comment]
I ended up implementing the array example, above.

**Comment by jfoclpf** [comment]
cool, it works the array

```javascript
colors.setTheme({
  link: ['underline', 'blue']
});
```

And that is cool that the order in the array is irrelevant. Perhaps you chose the array version exactly because of that!
