### ISSUE TITLE
--no-color switch is ignored

### ISSUE THREAD

**Issue by kelveden** [Marak/colors.js#90]
A simple test harness to illustrate:

```
require('colors');
console.log("hello".red);
```

Running `node test.js --no-color` results in "hello" in red rather than with no colour.

Having had a quick dig, I can see that the `colors.enabled` flag is being set to `false` correctly but the `applyStyle` function that uses the flag isn't being invoked.

**Comment by pksunkara** [comment]
This is fixed. Will release soon.
