### ISSUE TITLE
Disabling colors with a function

### ISSUE THREAD

**Issue by zpiman** [Marak/colors.js#96]
Would be nice if there is a way to disable the colors using a function call.
For example: 
```javascript
var colors = require('colors');

if(should_colors_be_off()) {
    colors.disable();
}

console.log("Hello World".red);
```

Would print: 
![Red](http://i.imgur.com/RXIoCCK.png) 
when `should_colors_be_off()` returns false
Otherwise it would print:
![White](http://i.imgur.com/rMnchSw.png)

**Comment by pksunkara** [comment]
Hello @zpiman, There is an option `colors.enabled` which you can modify after `require('colors')`. An example is given below

```js
var colors = require('colors');

if(should_colors_be_off()) {
    colors.enabled = false;
}

console.log("Hello World".red);
```

**Comment by zpiman** [comment]
Ok I have figured this one out in the meanwhile and completely forgot about this question. But thanks anyway!

**Comment by eprev** [comment]
It seems it doesn't work anymore.

```js
require('colors').enabled = false;
console.log('hello'.red);
```

It will print out red line.
